<?php

namespace Kwidoo\HexTools\Generators;

use Kwidoo\HexTools\Config\HexToolsConfig;
use Kwidoo\HexTools\Support\StubRenderer;

class PhpMdRulesetGenerator
{
    protected const STANDARD_RULES = ['codesize', 'design', 'naming', 'unusedcode'];

    public function __construct(
        protected HexToolsConfig $config,
        protected StubRenderer $renderer
    ) {}

    public function generate(): string
    {
        $phpmd = $this->config->get('phpmd', []);
        $thresholds = $phpmd['thresholds'] ?? [];
        $mainRules = $phpmd['rules']['main'] ?? self::STANDARD_RULES;

        $extraRules = array_diff($mainRules, self::STANDARD_RULES);
        $enabledRules = '';
        foreach ($extraRules as $rule) {
            $enabledRules .= "    <rule ref=\"rulesets/{$rule}.xml\"/>\n";
        }

        return $this->renderer->render(
            $this->stubPath('phpmd.xml.stub'),
            [
                'ruleset_name' => 'Hex Tools PHPMD Rules',
                'description' => 'Laravel Hexagonal Architecture PHPMD ruleset generated by kwidoo/hex-tools.',
                'enabled_rules' => $enabledRules,
                'cyclomatic_complexity_report_level' => (string) ($thresholds['cyclomatic_complexity_report_level'] ?? 10),
                'npath_complexity_report_level' => (string) ($thresholds['npath_complexity_report_level'] ?? 200),
                'excessive_method_length_minimum' => (string) ($thresholds['excessive_method_length_minimum'] ?? 80),
                'excessive_class_length_minimum' => (string) ($thresholds['excessive_class_length_minimum'] ?? 400),
                'too_many_methods_maxmethods' => (string) ($thresholds['too_many_methods_maxmethods'] ?? 20),
                'too_many_public_methods_maxmethods' => (string) ($thresholds['too_many_public_methods_maxmethods'] ?? 15),
                'coupling_between_objects_maximum' => (string) ($thresholds['coupling_between_objects_maximum'] ?? 13),
            ]
        );
    }

    protected function stubPath(string $stub): string
    {
        return dirname(__DIR__, 2) . '/stubs/' . $stub;
    }
}
