<?php

namespace Kwidoo\HexTools\Generators;

use Kwidoo\HexTools\Config\HexToolsConfig;
use Kwidoo\HexTools\Support\StubRenderer;

class PhpMdRulesetGenerator
{
    protected const STANDARD_RULES = ['codesize', 'design', 'naming', 'unusedcode'];

    public function __construct(
        protected HexToolsConfig $config,
        protected StubRenderer $renderer
    ) {}

    /**
     * Generate the main PHPMD ruleset.
     */
    public function generate(): string
    {
        return $this->generateForLayer('main');
    }

    /**
     * Generate a PHPMD ruleset for a specific layer.
     */
    public function generateForLayer(string $layer): string
    {
        $phpmd = $this->config->get('phpmd', []);
        $thresholds = $phpmd['thresholds'] ?? [];
        $rules = $phpmd['rules'][$layer] ?? $phpmd['rules']['main'] ?? self::STANDARD_RULES;

        $extraRules = array_diff($rules, self::STANDARD_RULES);
        $enabledRules = '';
        foreach ($extraRules as $rule) {
            $enabledRules .= "    <rule ref=\"rulesets/{$rule}.xml\"/>\n";
        }

        $layerLabel = ucfirst($layer);
        $description = match ($layer) {
            'domain' => 'PHPMD ruleset for Domain layer - enforces strict clean code principles.',
            'application' => 'PHPMD ruleset for Application layer - balances flexibility with maintainability.',
            default => 'Laravel Hexagonal Architecture PHPMD ruleset generated by kwidoo/hex-tools.',
        };

        return $this->renderer->render(
            $this->stubPath('phpmd.xml.stub'),
            [
                'ruleset_name' => "Hex Tools PHPMD Rules ({$layerLabel})",
                'description' => $description,
                'enabled_rules' => $enabledRules,
                'cyclomatic_complexity_report_level' => (string) ($thresholds['cyclomatic_complexity_report_level'] ?? 10),
                'npath_complexity_report_level' => (string) ($thresholds['npath_complexity_report_level'] ?? 200),
                'excessive_method_length_minimum' => (string) ($thresholds['excessive_method_length_minimum'] ?? 80),
                'excessive_class_length_minimum' => (string) ($thresholds['excessive_class_length_minimum'] ?? 400),
                'too_many_methods_maxmethods' => (string) ($thresholds['too_many_methods_maxmethods'] ?? 20),
                'too_many_public_methods_maxmethods' => (string) ($thresholds['too_many_public_methods_maxmethods'] ?? 15),
                'coupling_between_objects_maximum' => (string) ($thresholds['coupling_between_objects_maximum'] ?? 13),
            ]
        );
    }

    protected function stubPath(string $stub): string
    {
        return dirname(__DIR__, 2) . '/stubs/' . $stub;
    }
}
