<?php

afterEach(function () {
    // No files generated by doctor, nothing to clean up
});

it('runs successfully and outputs tool statuses', function () {
    $this->artisan('hex:doctor')->assertSuccessful();
});

it('outputs JSON when --format=json flag is passed', function () {
    $this->artisan('hex:doctor', ['--format' => 'json'])
        ->assertSuccessful()
        ->expectsOutputToContain('"tools"');
});

it('outputs tool names in table mode', function () {
    $this->artisan('hex:doctor')
        ->assertSuccessful()
        ->expectsOutputToContain('Deptrac')
        ->expectsOutputToContain('PHPStan')
        ->expectsOutputToContain('PHPMD')
        ->expectsOutputToContain('Pint')
        ->expectsOutputToContain('Rector');
});

it('outputs config file names', function () {
    $this->artisan('hex:doctor')
        ->assertSuccessful()
        ->expectsOutputToContain('deptrac.layers.yaml')
        ->expectsOutputToContain('phpstan.neon.dist')
        ->expectsOutputToContain('phpmd.xml')
        ->expectsOutputToContain('pint.json')
        ->expectsOutputToContain('rector.php');
});

it('includes suggested next steps', function () {
    $this->artisan('hex:doctor')
        ->assertSuccessful()
        ->expectsOutputToContain('Recommended next steps');
});

it('returns failure with --strict when important tools are missing', function () {
    $this->artisan('hex:doctor', ['--strict' => true])
        ->assertFailed();
});

it('returns success with --strict when all important items exist', function () {
    $base = $this->app->basePath('');

    $files = [
        'deptrac.layers.yaml', 'deptrac.modules.yaml',
        'phpstan.neon.dist', 'phpstan-domain.neon', 'phpstan-application.neon',
        'phpmd.xml', 'pint.json', 'rector.php',
    ];

    foreach ($files as $file) {
        file_put_contents("{$base}/{$file}", 'placeholder');
    }

    $binaries = [
        'vendor/bin/deptrac', 'vendor/bin/phpstan',
        'vendor/bin/phpmd', 'vendor/bin/pint', 'vendor/bin/rector',
    ];

    foreach ($binaries as $bin) {
        $dir = dirname("{$base}/{$bin}");
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }
        file_put_contents("{$base}/{$bin}", '#!/bin/sh');
        chmod("{$base}/{$bin}", 0755);
    }

    $this->artisan('hex:doctor', ['--strict' => true])
        ->assertSuccessful();

    foreach (array_merge($files, $binaries) as $path) {
        @unlink("{$base}/{$path}");
    }
});

it('skips unavailable tools during --run-checks', function () {
    $this->artisan('hex:doctor', ['--run-checks' => true])
        ->assertSuccessful();
});

it('outputs table format when --format=table flag is passed', function () {
    $this->artisan('hex:doctor', ['--format' => 'table'])
        ->assertSuccessful()
        ->expectsOutputToContain('Hex Tools Doctor');
});

it('has only one hex:doctor command registered', function () {
    $commands = $this->app->make(\Illuminate\Console\Application::class)->all();
    $doctorCommands = array_filter($commands, fn ($command) => $command->getName() === 'hex:doctor');
    expect(count($doctorCommands))->toBe(1);
});
